export * from './about/about-page.component';
export * from './card/card-page.component';
export * from './contact/contact-page.component';
export * from './favorite/favorite-page.component';
export * from './home/home.component';
export * from './patient/patient-page.component';
export * from './product/product-page.component';
export * from './search/search-page.component';
export * from './signup/signup-page.component';
